### ISSUE TITLE
Can we use pure rust?

### ISSUE THREAD

**Issue by neuodev** [itchyny/uptime-rs#3]
I noticed we are using some other packages to get the uptime. This might be unnecessary as we can still use pure rust to do it for example on Linux we can read [`/proc/uptime`](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-uptime) directly and the output should be something like this 
```bash
# in seconds
350735.47 234388.90
```

The windows crate is about **`12MB`** in size!
What about using a solution that goes like this 
````rs
let child = Command::new("systeminfo").output()?.stdout;
let output = String::from_utf8(child)?;
// ... extract the uptime from the output
```

**Comment by itchyny** [comment]
I think invoking lower apis is more reliable and performant than opening a proc file or forking a command. And about the crate size problem, I'm not an expert of Windows crates but accepting #2 was bad?

**Comment by neuodev** [comment]
Not bad of course. My point is this crate is too simple but yet it depends on 2 other bigger crates. 
I think it is still valid tho as we only select a specific feature out of the `windows` crate

```toml
[target.'cfg(windows)'.dependencies.windows]
version = "0.39.0"
features = ["Win32_System_SystemInformation"]
```
Thanks for the response! 
Feel free to close the issue!

**Comment by itchyny** [comment]
> I think it is still valid tho as we only select a specific feature out of the windows crate

I think we already do this but not applied or something?

**Comment by neuodev** [comment]
yes, we do. it is already in the TOML file
