### ISSUE TITLE
counter is zero,  but loadavg is not.

### ISSUE THREAD

**Issue by 21pages** [itchyny/uptime-rs#5]
![1690021307933](https://github.com/itchyny/uptime-rs/assets/14891774/604aaf24-fe19-4bb5-b1ec-e9d366b4bc0e)

**Comment by itchyny** [comment]
I'm not sure what you are talking about. This library has nothing to do with loadavg.

**Comment by 21pages** [comment]
Load Average is in the last line of the picture.
![1690065536001](https://github.com/itchyny/uptime-rs/assets/14891774/ae2910a7-5883-4755-bdc5-c15084714b62)

**Comment by itchyny** [comment]
What is the problem? Describe the issue with reproducible code and what you expect.

**Comment by 21pages** [comment]
1. The CPU usage is significantly smaller than that displayed by taskManager.
2. Is it reasonable to infer the average value of 1, 5, and 15 minutes based on the obtained two values

**Comment by itchyny** [comment]
This library does not provide CPU usage. You're reporting to a wrong repository.

**Comment by 21pages** [comment]
Yes, sorry for that
